version: 2.0.1
os: linux
files:
  - source: /
    destination: /home/ubuntu/ordertron-aws
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu